import { PhotoParams } from './photo-params.type';

export const PhotoParamsSource: PhotoParams[] = [
  {
    scene: '银河',
    type: '专业模式',
    zoomRatio: 1,
    meteringMode: '矩阵测光',
    iso: 800,
    shutterSpeed: 25,
    focusingMode: 'MF',
    whiteBalance: 4000,
  },
  {
    scene: '日落',
    type: '专业模式',
    zoomRatio: 1,
    meteringMode: '矩阵测光',
    iso: 50,
    shutterSpeed: '1/80',
    focusingMode: 'MF',
    whiteBalance: 6400,
  },
  {
    scene: '月亮',
    type: '专业模式',
    zoomRatio: 'Max',
    meteringMode: '矩阵测光',
    iso: 400,
    shutterSpeed: '1/200',
    focusingMode: 'MF',
    whiteBalance: 6700,
  },
  {
    scene: '夜晚星空',
    type: '专业模式',
    zoomRatio: 1,
    meteringMode: '矩阵测光',
    iso: 800,
    shutterSpeed: 15,
    focusingMode: 'MF',
    whiteBalance: 3800,
  },
  {
    scene: '夜空烟火',
    type: '专业模式',
    zoomRatio: 1,
    meteringMode: '矩阵测光',
    iso: 160,
    shutterSpeed: 4,
    focusingMode: 'AF-C',
    whiteBalance: 4200,
  },
  {
    scene: '夜景',
    type: '专业模式',
    zoomRatio: 1,
    meteringMode: '中央重点测光',
    iso: 100,
    shutterSpeed: 1.6,
    focusingMode: 'AF-S',
    whiteBalance: 6400,
  },
  {
    scene: '夜景车流',
    type: '专业模式',
    zoomRatio: 1,
    meteringMode: '中央重点测光',
    iso: 100,
    shutterSpeed: 1.6,
    focusingMode: 'AF-S',
    whiteBalance: 6200,
  },
  {
    scene: '下雨',
    type: '专业模式',
    zoomRatio: 1,
    meteringMode: '矩阵测光',
    iso: 100,
    shutterSpeed: '1/17',
    focusingMode: 'MF',
    whiteBalance: '阴天',
  },
  {
    scene: '街景',
    type: '专业模式',
    zoomRatio: 1,
    meteringMode: '中央重点测光',
    iso: 100,
    shutterSpeed: 1.6,
    focusingMode: 'AF-S',
    whiteBalance: 6200,
  },
  {
    scene: '秋天树叶',
    type: '专业模式',
    zoomRatio: 1,
    meteringMode: '矩阵测光',
    iso: 200,
    shutterSpeed: '1/40',
    focusingMode: 'AF-C',
    whiteBalance: 6400,
  },
];
